// Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
//
// MIT License

// Handle loading and testing of images

#include <stdio.h>
#include <include.h>
#include <apio.h>
#include <epio.h>
#include <test/stub.h>
#include <test/func.h>

typedef enum {
    TRANSFORM_NONE,
    TRANSFORM_DUPLICATE,
    TRANSFORM_TRUNCATE,
    TRANSFORM_PAD,
} rom_transform_t;

typedef struct {
    // When the firmware inputs are generated, ROMs are indexed starting at 0,
    // for example output/images/0.rom, 1.rom, etc.  This is that index.
    uint8_t build_index;

    // The index of the set of ROM images this ROM image apples to.  The
    // firmware generator starts with set 0, image 0, then moves to set 0,
    // image 1, etc. 
    uint8_t set_index;

    // The index of the image within the set.sdrr_info.metadata_header->rom_set_count
    uint8_t image_index;

    uint8_t pad;

    char *name;

    // The actual ROM image data, loaded from the file generated by sdrr-gen.
    uint8_t *data;

    // Actual size on disk
    uint32_t file_size;

    // Type of transformation applied to data
    rom_transform_t transform;
} test_src_rom_image_t;

// Array of pointers to ROM sources images, index by the build_index.
#define TST_MAX_ROM_IMAGES 64
_Static_assert(TST_MAX_ROM_IMAGES < 256, "TST_MAX_ROM_IMAGES must be less than 256 to fit in build_index");
static test_src_rom_image_t src_rom_images[TST_MAX_ROM_IMAGES];

#define TST_MAX_ROM_IMAGE_SIZE  (512*1024)

#define OUTPUT_IMAGE_DIR "../output/images"

static void load_src_rom_images(void) {
    memset(src_rom_images, 0, sizeof(src_rom_images));

    uint8_t next_set_index = 0;
    uint8_t next_image_index = 0;
    uint8_t total_sets = SDRR_NUM_SETS;
    uint8_t total_images = SDRR_NUM_IMAGES;
    for (int ii = 0; ii < total_images; ii++) {
        assert(next_set_index < total_sets && "More ROM images than expected");

        // Open the image
        char filename[256];
        snprintf(filename, sizeof(filename), "%s/%d.rom", OUTPUT_IMAGE_DIR, ii);
        FILE *file = fopen(filename, "rb");
        assert(file && "Failed to open ROM image file");

        // Get the file size
        fseek(file, 0, SEEK_END);
        long file_size = ftell(file);
        fseek(file, 0, SEEK_SET);
        assert(file_size <= TST_MAX_ROM_IMAGE_SIZE && "ROM image is too large");

        // Read the file into memory
        uint8_t *buffer = malloc(file_size);
        assert(buffer && "Failed to allocate memory for ROM image");
        fread(buffer, 1, file_size, file);
        fclose(file);

        // Store the image data and metadata
        src_rom_images[ii].build_index = ii;
        src_rom_images[ii].set_index = next_set_index;
        src_rom_images[ii].image_index = next_image_index;
        src_rom_images[ii].name = strdup(filename);
        src_rom_images[ii].data = buffer;
        src_rom_images[ii].file_size = (uint32_t)file_size;

        char info_filename[256];
        snprintf(info_filename, sizeof(info_filename), "%s/%d.info", OUTPUT_IMAGE_DIR, ii);
        FILE *info_file = fopen(info_filename, "r");
        assert(info_file && "Failed to open ROM info file");
        char transform_str[32] = {0};
        fgets(transform_str, sizeof(transform_str), info_file);
        fclose(info_file);

        if (strcmp(transform_str, "duplicate") == 0) {
            src_rom_images[ii].transform = TRANSFORM_DUPLICATE;
        } else if (strcmp(transform_str, "pad") == 0) {
            src_rom_images[ii].transform = TRANSFORM_PAD;
        } else if (strcmp(transform_str, "truncate") == 0) {
            src_rom_images[ii].transform = TRANSFORM_TRUNCATE;
        } else {
            src_rom_images[ii].transform = TRANSFORM_NONE;
        }

        TST_LOG("Loaded ROM image: %s (set %d image %d size %ld bytes, transform %s)", filename, next_set_index, next_image_index, file_size, transform_to_str[src_rom_images[ii].transform]);

        // Figure out the next set and image index
        next_image_index++;
        if (next_image_index >= rom_set[next_set_index].rom_count) {
            next_image_index = 0;
            next_set_index++;
        }
    }

    if ((next_set_index == 0) && (next_image_index == 0)) {
        TST_LOG("No ROM images loaded\n");
    }
}

void free_src_rom_images(void) {
    for (int ii = 0; ii < TST_MAX_ROM_IMAGES; ii++) {
        if (src_rom_images[ii].data != NULL) {
            free(src_rom_images[ii].data);
            src_rom_images[ii].data = NULL;
        }
        if (src_rom_images[ii].name != NULL) {
            free(src_rom_images[ii].name);
            src_rom_images[ii].name = NULL;
        }
    }
}

void setup_rom_images(void) {
    load_src_rom_images();
}

static test_src_rom_image_t *find_src_rom_image(uint8_t set_index, uint8_t image_index) {
    test_src_rom_image_t *image = NULL;
    for (int ii = 0; ii < TST_MAX_ROM_IMAGES; ii++) {
        if ((src_rom_images[ii].set_index == set_index) && (src_rom_images[ii].image_index == image_index)) {
            image = &src_rom_images[ii];
            break;
        }
    }

    assert(image != NULL && "ROM image not found for set and image index");
    if ((image->set_index != set_index) || (image->image_index != image_index)) {
        TST_LOG("ROM image metadata mismatch for set %d image %d: expected set_index %d image_index %d but got set_index %d image_index %d",
            set_index, image_index, set_index, image_index, image->set_index, image->image_index);
        assert(0 && "ROM image metadata mismatch");
    }

    return image;
}

// Get the appropriate ROM image data for a given set and image index.
const uint8_t *get_src_rom_image_data(uint8_t set_index, uint8_t image_index) {
    assert(set_index < SDRR_NUM_SETS && "Set index out of range");
    assert(image_index < rom_set[set_index].rom_count && "Image index out of range");
    test_src_rom_image_t *image = find_src_rom_image(set_index, image_index);
    assert(image != NULL && "ROM image not found for set and image index");
    return image->data;
}

sdrr_rom_type_t get_rom_type(uint8_t set_index, uint8_t image_index) {
    assert(set_index < SDRR_NUM_SETS && "Set index out of range");
    assert(image_index < rom_set[set_index].rom_count && "Image index out of range");
    const sdrr_rom_info_t *rom_info = rom_set[set_index].roms[image_index];
    assert(rom_info->rom_type < NUM_CHIP_TYPES && "Invalid ROM type");
    return rom_info->rom_type;
}

uint32_t get_rom_image_size(uint8_t set_index, uint8_t image_index) {
    assert(set_index < SDRR_NUM_SETS && "Set index out of range");
    assert(image_index < rom_set[set_index].rom_count && "Image index out of range");
    const sdrr_rom_info_t *rom_info = rom_set[set_index].roms[image_index];
    assert(rom_info->rom_type < NUM_CHIP_TYPES && "Invalid ROM type");
    uint32_t chip_size = chip_size_from_type[rom_info->rom_type];
    if (rom_info->rom_type == CHIP_TYPE_27C080) {
        // We only expect to read 512KB not 1MB
        chip_size /= 2;
        assert(chip_size == 512*1024 && "Unexpected ROM size for 27C080");
    }
    return chip_size;
}

uint8_t get_rom_image_data_byte(uint8_t set_index, uint8_t image_index, uint32_t addr) {
    test_src_rom_image_t *image = find_src_rom_image(set_index, image_index);
    assert(image != NULL && "ROM image not found");
    uint32_t chip_size = get_rom_image_size(set_index, image_index);
    assert(addr < chip_size && "Address out of range for ROM image");

    switch (image->transform) {
        case TRANSFORM_DUPLICATE:
            return image->data[addr % image->file_size];
        case TRANSFORM_PAD:
            return addr < image->file_size ? image->data[addr] : 0xAA;
        case TRANSFORM_TRUNCATE:
        case TRANSFORM_NONE:
        default:
            assert(addr < image->file_size && "Address out of range for raw image");
            return image->data[addr];
    }
}

const char *get_rom_image_name(uint8_t set_index, uint8_t image_index) {
    return rom_set[set_index].roms[image_index]->filename;
}