// Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
//
// MIT License

//! Raw, unsafe FFI bindings generated by bindgen from the firmware C headers.
//!
//! All symbols here map 1:1 to their C counterparts with no safety guarantees.
//! Use the safe wrapper [`crate::Emulator`] instead - the `emulator` module it
//! comes from is private, so link the re-export rather than the module.
//!
//! The generated source lives at `$OUT_DIR/bindings.rs`; inspect that file
//! after the first `cargo build` to see actual types and signatures.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]
#![allow(unsafe_op_in_unsafe_fn)]
// bindgen copies the C headers' Doxygen comments through, and rustdoc reads
// their `[in]` / `[out]` parameter annotations as intra-doc links it cannot
// resolve.  Nothing here is hand-written, so there is nothing to correct at
// source; suppress it for the generated bindings only.
#![allow(rustdoc::broken_intra_doc_links)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
