// Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
//
// MIT License

//! Build script for One ROM Lens.
//!
//! Two jobs, both host-side (build scripts always compile for the host):
//!
//! 1. **Embed the pin geometry.**  Parse `CONFIG` for `BOARD` and compute the
//!    address/data GPIO lists and control lines with `onerom-fw-geometry`'s pure
//!    `PinCache::build`, then emit them as consts (`$OUT_DIR/geometry.rs`).  The
//!    wasm runtime reads these consts — it never runs the generator itself, and
//!    a new `CsLogic`/`CsConfig` variant becomes a build-time error here rather
//!    than a browser-time surprise.
//! 2. **Emit wasm-only link flags** for the cdylib (see `wasm_link_args`).

use std::{env, fmt::Write as _, fs, path::PathBuf};

use onerom_config::chip::ChipType;
use onerom_config::hw::Board;
use onerom_fw_geometry::pin_cache::PinCache;
use onerom_fw_geometry::substitution::chip_substitution;
use onerom_gen::Config;

fn main() {
    embed_geometry();
    wasm_link_args();
}

/// Resolve `CONFIG` (relative to `BASE_DIR`, defaulting to the project root) and
/// emit the pin geometry for the first chip of its first chip set.
fn embed_geometry() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // project/rust/lens → two parents → project/
    let project_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("missing project root")
        .to_path_buf();

    let config = env::var("CONFIG")
        .unwrap_or_else(|_| panic!("CONFIG must be set (e.g. CONFIG=onerom-config/test-0.json)"));
    let board_str =
        env::var("BOARD").unwrap_or_else(|_| panic!("BOARD must be set (e.g. BOARD=fire-24-a)"));

    let base_dir = env::var("BASE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| project_root.clone());
    let config_path = {
        let p = PathBuf::from(&config);
        if p.is_absolute() {
            p
        } else {
            base_dir.join(&p)
        }
    };
    println!("cargo:rerun-if-env-changed=CONFIG");
    println!("cargo:rerun-if-env-changed=BOARD");
    println!("cargo:rerun-if-env-changed=BASE_DIR");
    println!("cargo:rerun-if-changed={}", config_path.display());

    let json = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("cannot read CONFIG '{}': {e}", config_path.display()));
    let cfg: Config = serde_json::from_str(&json)
        .unwrap_or_else(|e| panic!("cannot parse CONFIG '{}': {e}", config_path.display()));
    let board =
        Board::try_from_str(&board_str).unwrap_or_else(|| panic!("unknown BOARD '{board_str}'"));

    // Lens visualises the first chip of the first chip set.
    let chip_set = cfg
        .chip_sets
        .first()
        .unwrap_or_else(|| panic!("CONFIG has no chip sets"));
    let chip_config = chip_set
        .chips
        .first()
        .unwrap_or_else(|| panic!("CONFIG chip set 0 has no chips"));
    // Apply board-specific chip substitution (e.g. fire-32-a serves an
    // SST39SF040 as a 27C040), so lens drives exactly what the firmware serves.
    let requested = chip_config.chip_type.resolved();
    let chip_type = chip_substitution(board, requested).unwrap_or(requested);

    // Pure: derives GPIO lists + control lines from the board socket map and the
    // chip's CS polarities.  Panics (failing the build) on an unsupported config.
    let cache = PinCache::build(chip_type, chip_config, board);

    let mut out = String::new();
    out.push_str("// @generated by onerom-lens build.rs — do not edit.\n\n");

    // Address GPIOs: one entry per address bit; each is the list of MCU GPIOs
    // wired to that socket pin (>1 on fly-lead boards).
    out.push_str("pub const ADDR_GPIOS: &[&[u8]] = &[\n");
    for gpios in &cache.addr_gpios {
        writeln!(out, "    &{},", fmt_u8_slice(gpios)).unwrap();
    }
    out.push_str("];\n\n");

    writeln!(
        out,
        "pub const DATA_GPIOS: &[u8] = &{};\n",
        fmt_u8_slice(&cache.data_gpios)
    )
    .unwrap();

    // Control lines (CE/OE/CS + oversized-ROM half-selects), assertion polarity
    // baked in.  `commoned` is a multi-set-primary tester concern; not embedded.
    out.push_str("pub struct GeomControlLine {\n");
    out.push_str("    pub name: &'static str,\n");
    out.push_str("    pub gpios: &'static [u8],\n");
    out.push_str("    pub assert_high: bool,\n");
    out.push_str("}\n\n");
    out.push_str("pub const CONTROL_LINES: &[GeomControlLine] = &[\n");
    for cl in &cache.control_lines {
        writeln!(
            out,
            "    GeomControlLine {{ name: {:?}, gpios: &{}, assert_high: {} }},",
            cl.name,
            fmt_u8_slice(&cl.gpios),
            cl.assert_high
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    match cache.byte_n_gpio {
        Some(g) => writeln!(out, "pub const BYTE_N_GPIO: Option<u8> = Some({g});").unwrap(),
        None => out.push_str("pub const BYTE_N_GPIO: Option<u8> = None;\n"),
    }

    writeln!(
        out,
        "pub const NUM_ADDR_BITS: usize = {};",
        cache.addr_gpios.len()
    )
    .unwrap();
    writeln!(
        out,
        "pub const NUM_DATA_BITS: usize = {};",
        cache.data_gpios.len()
    )
    .unwrap();

    // DMA word size: 16-bit for the wide 27C200/27C400, else 8-bit.
    let word_size = if matches!(chip_type, ChipType::Chip27C400 | ChipType::Chip27C200) {
        16u8
    } else {
        8u8
    };
    writeln!(out, "pub const WORD_SIZE: u8 = {word_size};").unwrap();

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("geometry.rs");
    fs::write(&out_path, out).expect("cannot write geometry.rs");
}

/// Format a `&[u8]` as a Rust array literal, e.g. `[12u8, 13, 14]`.
fn fmt_u8_slice(v: &[u8]) -> String {
    let mut s = String::from("[");
    for (i, b) in v.iter().enumerate() {
        if i == 0 {
            write!(s, "{b}u8").unwrap();
        } else {
            write!(s, ", {b}").unwrap();
        }
    }
    s.push(']');
    s
}

/// The exported C ABI, as Emscripten `_`-prefixed names.  Emscripten dead-strips
/// everything not listed here (or referenced by `main`), so this must track the
/// `#[no_mangle]` functions in `main.rs`.
const EXPORTS: &[&str] = &[
    "_main",
    "_onerom_init",
    "_onerom_drive_addr",
    "_onerom_release_pins",
    "_onerom_step",
    "_onerom_read_data",
    "_onerom_read_pin_states",
    "_onerom_read_driven_pins",
    "_onerom_get_cycle_count",
    "_onerom_reset_cycle_count",
    "_onerom_get_sysclk_mhz",
    "_onerom_get_addr_pin",
    "_onerom_get_data_pin",
    "_onerom_lens_get_num_control_lines",
    "_onerom_get_control_pin",
    "_onerom_get_control_assert_high",
    "_onerom_get_cs1_pin",
    "_onerom_get_cs2_pin",
    "_onerom_get_cs3_pin",
    "_onerom_get_ce_pin",
    "_onerom_get_oe_pin",
    "_onerom_get_x1_pin",
    "_onerom_get_x2_pin",
    "_onerom_get_byte_pin",
    "_onerom_get_gpio_input_inverted",
    "_onerom_get_pio_disassembly",
    "_onerom_lens_get_num_addr_bits",
    "_onerom_lens_get_num_data_bits",
    "_onerom_lens_get_rom_size",
];

/// Emscripten/wasm-only link configuration.  `rustc-link-arg-bins` applies only
/// to this crate's own final link, and only when targeting wasm — never to a
/// dependency, and never to the C library `onerom-fw-emulator`'s build script
/// produces.
fn wasm_link_args() {
    if env::var("CARGO_CFG_TARGET_ARCH").as_deref() != Ok("wasm32") {
        return;
    }

    let arg = |a: &str| println!("cargo:rustc-link-arg-bins={a}");

    // Emit a MODULARIZE'd loader (factory `OneRomLens()`), keep the runtime alive
    // after `main` so the browser can call in later, expose ccall/cwrap, and grow
    // memory as capture buffers do.
    arg("-sMODULARIZE=1");
    arg("-sEXPORT_NAME=OneRomLens");
    arg("-sEXIT_RUNTIME=0");
    arg("-sALLOW_MEMORY_GROWTH=1");
    arg("-sEXPORTED_RUNTIME_METHODS=ccall,cwrap,UTF8ToString");
    arg(&format!("-sEXPORTED_FUNCTIONS={}", EXPORTS.join(",")));

    // Link the C++ runtime.  rustc drives emscripten through `emcc`, never
    // `em++`, and emscripten 6.0.6 flipped DEFAULT_TO_CXX to false — so from
    // that release libc++abi and libunwind stop being linked, and Rust's
    // prebuilt libstd/libpanic_unwind fail to resolve `__cpp_exception` and
    // `_Unwind_RaiseException`/`_Unwind_DeleteException`.  Re-asserting the old
    // default fixes the link and is a no-op on earlier emscripten.  The
    // otherwise-unused libc++ this drags in is dead-stripped.
    arg("-sDEFAULT_TO_CXX");

    // epio's wasm `libepio.a` redundantly bundles the apio disassembler
    // (apio_instruction_decoder / apio_log_sm) that the firmware also provides —
    // both come from apio_dis.h.  epio_apio.o is mandatory (it provides
    // epio_from_apio), so both copies reach the link.  wasm-ld keeps the first
    // (firmware's) and drops epio's redundant copy.  Scoped to this link only,
    // so it cannot mask duplicate symbols anywhere else.
    //
    // TODO(epio): remove once epio's reusable wasm library no longer ships the
    // apio disassembler implementation (tracked upstream in epio).
    arg("-Wl,--allow-multiple-definition");
}
